---
ansible_ssh_user: centos
ansible_ssh_private_key_file: knab.pem
DOCKER_VERSION: "18.09.0"
DOCKER_REPO_FILE_PATH: https://download.docker.com/linux/centos/docker-ce.repo
YUM_TARGET_REPO_FOLDER: /etc/yum.repos.d/docker-ce.repo
DOCKER_GPG_FILE_PATH: https://download.docker.com/linux/centos/gpg
GPG_TARGET_FOLDER: "/etc/pki"